apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deployment
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: myapp
        image: ahmad33/user-management:1.01
        ports:
        - containerPort: 8085
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: springapp-deployment
spec:
  selector:
    app: spring-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8085
    nodePort: 31110