apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deployment
  namespace: storage
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: myapp
        image: ahmad33/user-management:1.01
        ports:
        - containerPort: 8085
        env:                  # Environment variables supplied to the Pod
        - name: SPRING_DATASOURCE_USERNAME # Name of the environment variable
          valueFrom:          # Get the value of environment variable from kubernetes secrets
            secretKeyRef:
              name: mysecret
              key: mysql-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql-password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: url
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: springapp-deployment
  namespace: storage
spec:
  selector:
    app: spring-app 
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8085
    nodePort: 31113