apiVersion: v1
kind: Secret
metadata: 
    name: mysecret
    namespace: storage
type: Opaque
data:
  root: cm9vdA==
  mysql-root-password: YWRtaW4xMjM=
  mysql-user: YWhtYWRqdWJhaXI=
  mysql-password: UGFzc3dvcmRAMTIz